---
title: "Marketing and Market Microstructure"
format: html
---

## Introduction

In *Bayesians in the Catallaxy*, we spend a great deal of time connecting Mises and Hayek to de Finetti and modern finance. For example, we demonstrate that de Finetti's Fundamental Theory of Prevision is equivalent to the Fundamental Theorem of Asset Pricing. However, this market-making, entrepreneurial-focused, supply-side story says nothing about consumer demand. Certainly there is no market without a market-maker, but there is also no consumption without consumers. What is the connection between marketing and market microstructure?

Market microstructure is the study of how exchange occurs in financial markets. It is dominated by rational expectation equilibrium models where the market is in equilibrium and all agents are rational Bayesians except that information is asymmetric due to strategic behavior or "noisy" prices (i.e., "Bayesians in the Economy"). Marketing is the study of how exchange occurs in consumer markets. It is also beholden to neoclassical economics in the form of microeconomic models of demand that depend on rational expectations and utility maximization where consumers heterogeneously trade-off the prices and perceived quality of different goods and services.

Marketing and market microstructure are separately connected to Misesian valuation, the Hayekian knowledge problem, and subjective probability, albeit in different types of exchange. In order to explore the connection between marketing and market microstructure, we need to start with the primitives and then consider theories that may serve as common foundations before attempting to produce a unified theory of exchange.

- Does Buchanan discuss the inability to estimate demand in public choice?
- Profit-loss analogy in markets for the evaluation game?
- Sun-Abraham group-level estimates, specifically for event studies?
- What is a bandwidth in a regression discontinuity design?
- Purging humans from science results in mechanomorphism
- "Exact Thinking in Demented Times" for the Vienna Circle, for us
- The likelihood need not "bite" if we can operationalize institutions
- Does Greg's wants-and-needs work avoid utility maximization?
- Disequilibrium theory exposes the causal transmission of knowledge
- Can Bayesians in the Catallaxy become an Economic Rethinking?

## Prices, Preferences, and Probabilities

In neoclassical market microstructure, prices are first probabilities drawn from a "true" data-generating process. However, for de Finetti's subjective probability, probabilities are first prices drawn from a subjective data-generating process. The equivalent marketing primitive are preferences. These preferences may only be stable with respect to a consumer's willingness-to-pay (WTP) and thus more closely connected to prices and de Finetti.

"[T]he combined assumptions of maximizing behavior, market equilibrium, and stable preferences, used relentlessly and unflinchingly, form the heart of the economic approach as it is." (Gary Becker, *The Economic Approach to Human Behavior*) We contest the fact of a market equilibrium, but not the fact of maximizing behavior or stable preferences. "It is a theoremo of decision theory that any consistent set of preferences can be converted into an ordinal cost scale." (Kevin Murphy, *Probabilistic Machine Learning: An Introduction*)

Is this "Fundamental Theory of WTP" the marketing equivalent of the Fundamental Theorem of Asset Pricing and thus de Finetti's Theory of Prevision? If so, preferences (i.e., WTP) = prices = probabilities.

- Is WTP a prevision?
- What is supply-side marketing? Connected to institutional economics?

## Search and Bounded Rationality

Detail the connections between exchangeable search and bounded rationality and how this can be operationalized using agent-based modeling.

- Just like probability doesn't exist, equilibrium doesn't exist
- How do we go from bounded rationality to real options theory?

## Simultaneous Demand and Supply

"The fundamental question of option pricing is how much the option is worth at time zero before we know whether the coin toss results in head or tail." (The Binomial No-Arbitrage Pricing Model, p. 3.) Note that this is to set the price of the **option** not the price of the underlying **asset**. The spot price of the asset is assumed to be observable. However, certainly consumer demand for the underlying asset of an option contributes to how an option is priced.

- Are there finance models that simultaneoulsy model demand and supply in order to identify the spot price?
- Or is the spot price not endogenous to the options pricing model?

## Conclusion

