---
title: "Bayesians in the Catallaxy"
subtitle: "A Research Proposal"
citeproc: true
bibliography: biblio.bib
format: pdf
number-sections: true
abstract: This paper is about ***arbitrage trinitarianism***.
---

\vspace{5cm}

---

\vspace{5cm}

> *There has been a tremendous neglect of the notion of ... emergent choice; that we don't really have before us objects among which to choose. We create them in the act of choice...* ***Arbitrage really has not become central to economics like it should be.*** -- James M. Buchanan

\newpage

# Introduction: Triangular Arbitrage

> ***Economics is about arbitrage.*** *The behavioral paradigm central to economics is that of the trader whose Smithean propensity to truck and barter locates and creates opportunities for mutual gains. This paradigm is contrasted with that of the maximizing engineer who allocates scarce resources among alternatives.... the maximizing paradigm is the fatal methodological flaw in modern economics.* -- James M. Buchanan

We strongly agree with Nobel laureate James M. Buchanan: arbitrage has not become central to economics as it should be. This paper is fundamentally about arbitrage. At the intellectual level, we deliver a literal triangular arbitrage by examining and combining three separate research programs unified by a single underlying principle — the inherent role of arbitrage. Austrian catallactics, Bruno de Finetti’s operational subjective probability theory, and modern finance are three distinct areas of research each founded upon the arbitrage principle. But these foundations were developed in isolation of each other — they have not properly recognized each other as kindred. A synoptic reading of each literature reveals deep connections and opportunities for profound insight. We call this arbitrage trinitarianism: the unification of three separate literatures and the new ideas that emerge from their combination that none could achieve alone. Understanding this common foundation is more than an intellectual exercise; we use the insights obtained by a thorough understanding of these connections to develop a unified, empirically operational framework for modeling decisions.

In this proposal, we describe the three research programs of interest and hint at the strong connections between each discipline. Additionally, we introduce computational statistical catallactics, an operational methodology that leverages and applies the results of this intellectual arbitrage and which provides a framework for approaching a broad class of modeling and prediction questions.

The Journal of Economic Perspectives describes its own scholarly mission as providing “intellectual arbitrage” for economists. We propose that our project is exactly the type of intellectual arbitrage of inherent interest to readers of JEP.

In his 1979 book on economic methodology titled “What Should Economists Do?”, Buchanan states unambiguously and provocatively:

“Economics is about arbitrage. The behavioral paradigm central to economics is that of the trader whose Smithean propensity to truck and barter locates and creates opportunities for mutual gains. This paradigm is contrasted with that of the maximizing engineer who allocates scarce resources among alternatives…. the maximization paradigm is the fatal methodological flaw in modern economics.”

This paper is not a literature survey; it is a deep intellectual triangular arbitrage — one that motivates the development of a new economic methodology that will appeal to even the most mathematically-hesitant economists.

# Austrian Catallactics

The first pillar of the arbitrage triad is Austrian catallactics where we embrace some of the Austrian theory and ontology, while resisting some layers of it in the broader project of developing a mathematical model that bridges the gap between Austrian economics and traditional mathematical economist. We agree with Arthur (2023) that “the Austrian approach deserves a more central place in economic theory.” But rather than simply praise the Austrians and then just as quickly move past them, we intend to build directly upon their conception of the market as a competitive entrepreneurial discovery process (Hayek 2002; Buchanan and Vanberg 1991; Kirzner 1997; High 2012; and V. L. Smith 2015). First, we embrace Austrian critiques of traditional economic theory and some of its ontological foundations by acknowledging the open and irregular nature of the market system we are modeling (Lawson 2005 and 2015). Like the Austrians, we accept that such starting assumptions insufficiently model markets, however, we resist the conclusion that markets and agents cannot be mathematically modeled because of mathematical ontology.

Second, we embrace Mises’s emphasis on monetary calculation and intentional human action as providing the necessary foundations (Mises 2007a, 2007b, 2007c, 2007d; and Horwitz 2004). For Mises the entrepreneur is the “driving force of the market” and according to Kirzner ([1973] 2013) the Misesian entrepreneur provides “an arbitrage theory of profit.” We emphasize that the Mises-Hayek argument in this context was meant to undermine socialist calculation models in favor of entrepreneurial economic calculations in the face of epistemic and coordination problems (Boettke 1998; Horwitz 2004; Vaughn 1980). However, we resist the early Hayakian empiricist ontology that reduces all structures to subjective agent-based ones and instead opt for an ontology of real structures that are based on subjective agents and beliefs without being reducible to beliefs, concepts, and actions of human agents (Lawson, 2005, 150). Upon these foundations the market emerges as a spontaneous and open order from which we can study the epistemic properties of the price system without zero-sum transactions and the irrationality of some agents (Hayek 1937, 1945). By refocusing in these foundational ways, our model will also shift focus from predictive—future outcomes—towards descriptive—modeling economic mechanisms and thus represent an improvement over current macroeconomic models (Lawson 2005). Third, we emphasize that at the heart of Austrian catallatics is a latent theory of the price mechanism as a socially real quantitative process. The irony is that an operational model of this process has so far eluded economic theorists (Fisher 1983). By embracing some but not all the Austrian theory, we build an Arbitrage triad that bridges between traditional mathematical modeling and Austrian Catallactics.


# Bruno de Finetti’s Operational Subjective Probability

The second pillar focuses on developing and adopting an operational subjective probability. Here we take a nuanced ontological position, not only acknowledging the open nature of the economic system we aim to model but also affirming subjective Bayesian probabilities in place of objective probabilities at the agent level of the market (Lawson 2005 and 2015). Bruno de Finetti’s operational subjective probability theory is founded upon the Dutch book argument (DBA) (Vineberg 2022). At the heart of the

DBA is the logic of arbitrage. In fact, it is a theorem of no-arbitrage at the subjective level of the individual agent. This is the proper place for the concept of no-arbitrage. The DBA defines individual rational behavior as a coherent plan. We emphasize that de Finetti’s is an economic derivation of the axioms of probability and in this regard is entirely unique. De Finetti was as thoroughgoingly subjectivist as any Austrian economist. His concerns with epistemology and subjective knowledge are identical to those of Hayek (1948). By accepting subjective probability at the agent level but resisting the ontological reduction of all economic structures to the agent level of markets, we provide space for modeling how the agent’s beliefs, actions, and concepts give rise to various economic mechanisms and structures. With Kreps (1988b) we agree that De Finetti’s representation theorem is the fundamental theorem of operational statistics (see also Bernardo and Smith 1994; Lad 1996; McCall 1991; Poirier 2011). Remarkably, his Fundamental Theorem of Prevision is identical to the Fundamental Theorem of Asset Pricing (see Nau 1999, 2001, 2023; Nau and McCardle 1991; and Schervish, Seidenfeld, and Kadane 2008). De Finetti uniquely provides the subjective probability foundations for an operational theory of arbitrage as the driving force of the catallaxy. In doing so, he stands as the mechanistic bridge for a more accurate modeling of subjective probabilities in economic systems.

Notes from BG:

I suggest a terminology shift from ‘trinity’ to ‘triad’ to avoid confusion with the more typical religious use of ‘trinity’ and to increase clarity and decrease technical language.

# Arbitrage Foundations of Finance

> *[W]hen judged by its ability to explain the empirical data, option pricing theory is the most successful theory not only in finance, but in all of economics. It is now widely employed by the financial industry and its impact on economics has been far-ranging. At a theoretical level, we now understand that option pricing theory is a manifestation of the force of arbitrage and that this is the same force that underlies much of neoclassical finance.* -- Stephen A. Ross

- @Friedman1953 and Fama JB 1965
- The Fundamental Theorem of Asset Pricing
- Steve Ross on arbitrage intuition and no-arbitrage theory
- Market microstructure
    - It's equilibrium turtles all the way down.
- See NA (circular logic)
- @FiglewskiJFM2017


# Computational Statistical Catallactics

\newpage

# References
