---
title: "Bayesians in the Catallaxy"
subtitle: "A Research Proposal"
citeproc: true
bibliography: biblio.bib
format: pdf
number-sections: true
abstract: This paper is about ***triad arbitrage***.
---

\vspace{5cm}

---

\vspace{5cm}

> *There has been a tremendous neglect of the notion of ... emergent choice; that we don't really have before us objects among which to choose. We create them in the act of choice...* ***Arbitrage really has not become central to economics like it should be.*** -- James M. Buchanan

\newpage

# Introduction

We strongly agree with Nobel laureate James M. Buchanan: arbitrage has not become central to economics as it should be. This paper is fundamentally about arbitrage. At the intellectual level, we deliver a literal triangular arbitrage by examining and combining three separate research programs unified by a single underlying principle — the inherent role of arbitrage. Austrian catallactics, Bruno de Finetti’s operational subjective probability theory, and modern finance are three distinct areas of research each founded upon the arbitrage principle. But these foundations were developed in isolation of each other — they have not properly recognized each other as kindred. A synoptic reading of each literature reveals deep connections and opportunities for profound insight and collaboration. These three areas become the pillars of what we will call Triad Arbitrage. The combination of these areas gives rise to new ideas that none could achieve alone. We use the insights obtained by a thorough understanding of these connections to develop a unified, empirically operational framework for modeling decisions that both provides a more successful economic model and bridges the gap between classical economists and Austrian economists.

In the first three sections of this paper, we present the three pillars of the Triad Arbitrage followed by a fourth section devoted to the new methodology that we have developed based on these three pillars: computational statistical catallactics. Section one considers the first pillar, Austrian catallactics, where we develop the theoretical foundations we have adopted from both Austrian theory and classical economics with respect to both economic systems and agents. In section two, we present the second pillar, Bruno de Finetti’s operational subjective probability, where we argue for the compatibility of de Finetti with Austrian theory while also providing a mathematical modeling bridge to classical economics. Section three presents the third pillar, modern finance theory, where arbitrage theory is already worked out in some detail and we aim to develop it on the foundations of de Finetti, Mises, and Hayek. Finally, in section four, we introduce computational statistical catallactics, an operational methodology that leverages and applies the results of this intellectual arbitrage and which provides a framework for approaching a broad class of modeling and prediction questions.

# Austrian Catallactics

The first pillar of the arbitrage triad is Austrian catallactics where we embrace some of the Austrian theory and ontology and use this foundation to come to new conclusions, in the broader project of developing a computational model that bridges the gap between Austrian economics and traditional mathematical economics. We agree with Arthur (2023) that “the Austrian approach deserves a more central place in economic theory.” But rather than simply praise the Austrians and then just as quickly move past them, we intend to build directly upon their conception of the market as a competitive entrepreneurial discovery process (Hayek 2002; Buchanan and Vanberg 1991; Kirzner 1997; High 2012; and V. L. Smith 2015). First, we embrace Austrian critiques of traditional economic theory and some of its ontological foundations by acknowledging the open and irregular nature of the market system we are modeling (Lawson 2005 and 2015). Like the Austrians, we accept that such starting assumptions insufficiently model markets, however, we resist the conclusion that markets and agents cannot be mathematically modeled because of mathematical ontology.

Second, we embrace Mises’s emphasis on monetary calculation and intentional human action as providing the necessary foundations (Mises 2007a, 2007b, 2007c, 2007d; and Horwitz 2004). For Mises, the entrepreneur is the “driving force of the market” and according to Kirzner ([1973] 2013) the Misesian entrepreneur provides “an arbitrage theory of profit.” We emphasize that the Mises-Hayek argument in this context was meant to undermine socialist calculation models in favor of entrepreneurial economic calculations in the face of epistemic and coordination problems (Boettke 1998; Horwitz 2004; Vaughn 1980). However, we resist the early Hayekian empiricist ontology that reduces all structures to subjective agent-based ones and instead opt for an ontology of real structures that are based on subjective agents and beliefs without being reducible to beliefs, concepts, and actions of human agents (Lawson, 2005, 150). Upon these foundations the market emerges as a spontaneous and open order from which we can study the epistemic properties of the price system without zero-sum transactions and with the irrationality of some agents (Hayek 1937, 1945). By refocusing in these foundational ways, our model will also shift focus from predictive—future outcomes towards descriptive—modeling economic mechanisms and thus represent an improvement over current macroeconomic models (Lawson 2005). Third, we emphasize that at the heart of Austrian catallatics is a latent theory of the price mechanism as a socially real quantitative process. The irony is that an operational model of this process has so far eluded economic theorists (Fisher 1983). By embracing some but not all of Austrian theory, we build an arbitrage triad that bridges between traditional mathematical modeling and Austrian catallactics.


# Bruno de Finetti’s Operational Subjective Probability

The second pillar focuses on developing and adopting an operational subjective probability. Here we take a nuanced ontological position, not only acknowledging the open nature of the economic system we aim to model but also affirming subjective Bayesian probabilities in place of objective probabilities at the agent level of the market (Lawson 2005 and 2015). Bruno de Finetti’s operational subjective probability theory is founded upon the Dutch book argument (DBA) (Vineberg 2022). At the heart of the DBA is the logic of arbitrage. In fact, it is a theorem of no-arbitrage at the subjective level of the individual agent. This is the proper place for the concept of no-arbitrage. The DBA defines individual rational behavior as a coherent plan. From this, de Finetti derives the axioms of probability through an individual's rational economic behavior and in this regard is entirely unique. De Finetti was as thoroughgoingly subjectivist as any Austrian economist. His concerns with epistemology and subjective knowledge are identical to those of Hayek (1948). By accepting subjective probability at the agent level but resisting the ontological reduction of all economic structures to the agent level of markets, we provide space for modeling how the agent’s beliefs, actions, and concepts give rise to various economic mechanisms and structures. With Kreps (1988b), we agree that De Finetti’s representation theorem is the fundamental theorem of operational statistics (see also Bernardo and Smith 1994; Lad 1996; McCall 1991; Poirier 2011). Remarkably, his Fundamental Theorem of Prevision is identical to the Fundamental Theorem of Asset Pricing (see Nau 1999, 2001, 2023; Nau and McCardle 1991; and Schervish, Seidenfeld, and Kadane 2008). De Finetti uniquely provides the subjective probability foundations for an operational theory of arbitrage as the driving force of the catallaxy. In doing so, he stands as the mechanistic bridge for a more accurate modeling of subjective probabilities in economic systems.

## Editing Notes

Notes from BG:

I suggest a terminology shift from ‘trinity’ to ‘triad’ to avoid confusion with the more typical religious use of ‘trinity’ and to increase clarity and decrease technical language.

Notes from EB: 

We say here "and with the irrationality of some agents". I don't think this is quite what we mean. We do not allow for agent irrationality (in the sense that each agent obeys in their decisions the axioms of probability). Rather, we allow the subjective probabilities to differ and therefore everyone can make internally rational choices but which result in market movement. 

I also don't quite understand two things: 
It seems that the word subjective is used in two different ways in this one sentence: "However, we resist the early Hayekian empiricist ontology that reduces all structures to subjective agent-based ones and insteadopt for an ontology of real structures that are based on subjective agents and beliefs withoutbeing reducible to beliefs, concepts, and actions of human agents". I can't quite tell what the first part of the sentence means, so I can't correct it. 

The second issue is with the sentence "By accepting subjective probability at the agent level but resistingthe ontological reduction of all economic structures to the agent level of markets". Don't we want to be able to include the market as an agent in our models? This was how we were going to justify allowing everyone to act rationally without approaching the psychology of irrational decision-making. 

# Arbitrage Foundations of Finance

Perhaps not surprisingly, modern finace is the third pillar of the arbitrage trinity. As Figlewski
(2017) has said, “Arbitrage, or more precisely, the lack of profitable arbitrage opportunities, is what
drives our pricing models. Derivatives theory is based on the principle that when the same payoff
can be produced in two or more different ways in the market, arbitrage (true arbitrage!) must
force them all to be priced exactly the same.” Ross (1987) has very usefully (for our purposes)
distinguished between the intuition of modern finance and the theory of modern finance. According
to Ross, and we agree: “The theory is less a formal mathematical structure driven by its own
imperatives — although that is always a danger — as it is a handmaiden that attempts to bridge
the gap between the intuitions and the data.” Furthermore we agree with Dybvig and Ross (1989)
that “… the intuition of that the absence of arbitrage is more primitive than equilibrium, since only
relatively few rational agents are needed to bid away arbitrage opportunities, even in the presence of
a sea of agents driven by ‘animal spirits.’ ” Modern finance theory has been the one place where
arbitrage theory has been most thoroughly worked out, though not without some ambiguity and
confusion (as we will demonstrate). Nevertheless, there is much to learn from the formal methods of
finance theory that will be of great service to computational statistical catallactics. We conclude
with Fama (2014) that “finance is the most successful branch of economics in terms of rich theory,
extensive empirical tests, and penetration of the theory and evidence into other areas of economics
and real-world applications.” Though our explicit purpose is to replace the microfoundations of
finance built upon Arrow-Debreu and rational expectations with those of Mises, Hayek, and de
Finetti we nevertheless aspire to the same impressive combinations of powerful theory and empirical
predictive ability as modern finance. Indeed, as we will show the success of the latter has always
been due to a latent theory of catallactics and operationally subjective probability theory a la de
Finetti


# Computational Statistical Catallactics
- ACE is a method without a theory.
- Catallactics is a theory without a method.
- Mises-Hayek-de Finetti provide the necessary microfoundations

\newpage

# References
